import React from 'react';
import Icon from './Icon';

export const ArrowDown = props => <Icon {...props} name="ArrowDown" />;
export const ArrowLeft = props => <Icon {...props} name="ArrowLeft" />;
export const ArrowRight = props => <Icon {...props} name="ArrowRight" />;
export const ArrowUp = props => <Icon {...props} name="ArrowUp" />;
export const Back = props => <Icon {...props} name="Back" />;
export const Bus = props => <Icon {...props} name="Bus" />;
export const Calendar = props => <Icon {...props} name="Calendar" />;
export const CarSharing = props => <Icon {...props} name="Car Sharing" />;
export const Card = props => <Icon {...props} name="Card" />;
export const Change = props => <Icon {...props} name="Change" />;
export const Chat = props => <Icon {...props} name="Chat" />;
export const Child = props => <Icon {...props} name="Child" />;
export const Clock = props => <Icon {...props} name="Clock" />;
export const Close = props => <Icon {...props} name="Close" />;
export const Currency = props => <Icon {...props} name="Currency" />;
export const DifferentAirport = props => <Icon {...props} name="DifferentAirport" />;
export const DiscountCard = props => <Icon {...props} name="DiscountCard" />;
export const Dropdown = props => <Icon {...props} name="Dropdown" />;
export const Edit = props => <Icon {...props} name="Edit" />;
export const ExclamationO = props => <Icon {...props} name="Exclamation-o" />;
export const ExclamationTri = props => <Icon {...props} name="Exclamation-tri" />;
export const Exclamation = props => <Icon {...props} name="Exclamation" />;
export const Ferry = props => <Icon {...props} name="Ferry" />;
export const Filter = props => <Icon {...props} name="Filter" />;
export const Flight = props => <Icon {...props} name="Flight" />;
export const Hamburger = props => <Icon {...props} name="Hamburger" />;
export const Id = props => <Icon {...props} name="ID" />;
export const Infant = props => <Icon {...props} name="Infant" />;
export const InfoO = props => <Icon {...props} name="Info-o" />;
export const Info = props => <Icon {...props} name="Info" />;
export const Lock = props => <Icon {...props} name="Lock" />;
export const LuggageCarryOn = props => <Icon {...props} name="LuggageCarryOn" />;
export const LuggageCheckIn = props => <Icon {...props} name="LuggageCheckIn" />;
export const Mail = props => <Icon {...props} name="Mail" />;
export const Minus = props => <Icon {...props} name="Minus" />;
export const MobileTicket = props => <Icon {...props} name="Mobile-ticket" />;
export const MobileTicket2 = props => <Icon {...props} name="Mobile-ticket2" />;
export const Moon = props => <Icon {...props} name="Moon" />;
export const Multimodal = props => <Icon {...props} name="Multimodal" />;
export const Notification = props => <Icon {...props} name="Notification" />;
export const PassengerFull = props => <Icon {...props} name="PassengerFull" />;
export const Person = props => <Icon {...props} name="Person" />;
export const Pin = props => <Icon {...props} name="Pin" />;
export const PinStart = props => <Icon {...props} name="PinStart" />;
export const Plus = props => <Icon {...props} name="Plus" />;
export const Price = props => <Icon {...props} name="Price" />;
export const Rate = props => <Icon {...props} name="Rate" />;
export const Search = props => <Icon {...props} name="Search" />;
export const Seat = props => <Icon {...props} name="Seat" />;
export const ShareAndroid = props => <Icon {...props} name="Share Android" />;
export const ShareIOs = props => <Icon {...props} name="Share iOS" />;
export const Swapper = props => <Icon {...props} name="Swapper" />;
export const SwapperHorizontal = props => <Icon {...props} name="SwapperHorizontal" />;
export const Telephone = props => <Icon {...props} name="Telephone" />;
export const Tick = props => <Icon {...props} name="Tick" />;
export const Tick2 = props => <Icon {...props} name="Tick2" />;
export const Tickets = props => <Icon {...props} name="Tickets" />;
export const Train = props => <Icon {...props} name="Train" />;
export const Wc = props => <Icon {...props} name="Wc" />;
export const Wifi = props => <Icon {...props} name="Wifi" />;
export const Archive = props => <Icon {...props} name="archive" />;
export const Bike = props => <Icon {...props} name="bike" />;
export const Car = props => <Icon {...props} name="car" />;
export const CarExtraLarge = props => <Icon {...props} name="carExtraLarge" />;
export const CarLarge = props => <Icon {...props} name="carLarge" />;
export const CarRegular = props => <Icon {...props} name="carRegular" />;
export const Fb = props => <Icon {...props} name="fb" />;
export const Food = props => <Icon {...props} name="food" />;
export const Instagram = props => <Icon {...props} name="instagram" />;
export const Linkedin = props => <Icon {...props} name="linkedin" />;
export const Pets = props => <Icon {...props} name="pets" />;
export const Plug = props => <Icon {...props} name="plug" />;
export const PublicTransport = props => <Icon {...props} name="public transport" />;
export const Twitter = props => <Icon {...props} name="twitter" />;
export const Youtube = props => <Icon {...props} name="youtube" />;
